# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DNA_Alignment.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 337)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: rgb(34, 165, 241);\n"
"}\n"
"QTabBar::tab:selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"QTreeView, QListView\n"
"{\n"
"    background-color: rgb(34, 165, 241);\n"
"    margin-left: 5px;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #808080;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 1px solid darkgray;*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/dark_orange/img/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"    border: 1px solid darkgray;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: rgb(34, 165, 241);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: rgb(34, 165, 241);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/dark_orange/img/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: rgb(255,255,255);\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/dark_orange/img/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 8px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #3A3939;\n"
"    width: 8px;\n"
"    background: #201F1F;\n"
"    margin: 0 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
"      stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: 0 -4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    border: 1px solid darkgray;\n"
"\n"
"    border-radius: 2px;\n"
"    min-width: 50px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.browse_frame_1 = QtWidgets.QFrame(self.frame_3)
        self.browse_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.browse_frame_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.browse_frame_1.setObjectName("browse_frame_1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.browse_frame_1)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dna_viewer_1 = QtWidgets.QLineEdit(self.browse_frame_1)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.dna_viewer_1.setFont(font)
        self.dna_viewer_1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dna_viewer_1.setMouseTracking(False)
        self.dna_viewer_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dna_viewer_1.setAcceptDrops(False)
        self.dna_viewer_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"")
        self.dna_viewer_1.setInputMask("")
        self.dna_viewer_1.setText("")
        self.dna_viewer_1.setFrame(True)
        self.dna_viewer_1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.dna_viewer_1.setCursorPosition(0)
        self.dna_viewer_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dna_viewer_1.setDragEnabled(False)
        self.dna_viewer_1.setReadOnly(False)
        self.dna_viewer_1.setPlaceholderText("DNA 1")
        self.dna_viewer_1.setClearButtonEnabled(False)
        self.dna_viewer_1.setObjectName("dna_viewer_1")
        self.horizontalLayout_9.addWidget(self.dna_viewer_1)
        self.browse_button_1 = QtWidgets.QPushButton(self.browse_frame_1)
        self.browse_button_1.setEnabled(True)
        self.browse_button_1.setAutoFillBackground(False)
        self.browse_button_1.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 127);")
        self.browse_button_1.setFlat(False)
        self.browse_button_1.setObjectName("browse_button_1")
        self.horizontalLayout_9.addWidget(self.browse_button_1)
        self.verticalLayout_3.addWidget(self.browse_frame_1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_file_button = QtWidgets.QPushButton(self.frame_5)
        self.add_file_button.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 170, 0)")
        self.add_file_button.setObjectName("add_file_button")
        self.verticalLayout_2.addWidget(self.add_file_button)
        self.remove_file_button = QtWidgets.QPushButton(self.frame_5)
        self.remove_file_button.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(200,0, 0)")
        self.remove_file_button.setObjectName("remove_file_button")
        self.verticalLayout_2.addWidget(self.remove_file_button)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.calculate_button = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_button.sizePolicy().hasHeightForWidth())
        self.calculate_button.setSizePolicy(sizePolicy)
        self.calculate_button.setMinimumSize(QtCore.QSize(150, 0))
        self.calculate_button.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(170, 0, 255)")
        self.calculate_button.setObjectName("calculate_button")
        self.verticalLayout_6.addWidget(self.calculate_button)
        self.download_button = QtWidgets.QPushButton(self.frame_10)
        self.download_button.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 107, 88);")
        self.download_button.setObjectName("download_button")
        self.verticalLayout_6.addWidget(self.download_button)
        self.reset_button = QtWidgets.QPushButton(self.frame_10)
        self.reset_button.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(165, 186, 255)")
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout_6.addWidget(self.reset_button)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.horizontalLayout.addWidget(self.frame)
        self.alignment_type_frame = QtWidgets.QFrame(self.frame_2)
        self.alignment_type_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.alignment_type_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.alignment_type_frame.setObjectName("alignment_type_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.alignment_type_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.alignment_type_frame_1 = QtWidgets.QFrame(self.alignment_type_frame)
        self.alignment_type_frame_1.setMinimumSize(QtCore.QSize(205, 45))
        self.alignment_type_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.alignment_type_frame_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.alignment_type_frame_1.setObjectName("alignment_type_frame_1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.alignment_type_frame_1)
        self.horizontalLayout_12.setContentsMargins(50, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pairwise_alignment = QtWidgets.QRadioButton(self.alignment_type_frame_1)
        self.pairwise_alignment.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pairwise_alignment.setObjectName("pairwise_alignment")
        self.horizontalLayout_12.addWidget(self.pairwise_alignment)
        self.multi_alignment = QtWidgets.QRadioButton(self.alignment_type_frame_1)
        self.multi_alignment.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);;")
        self.multi_alignment.setObjectName("multi_alignment")
        self.horizontalLayout_12.addWidget(self.multi_alignment)
        self.verticalLayout.addWidget(self.alignment_type_frame_1)
        self.alignment_type_frame_2 = QtWidgets.QFrame(self.alignment_type_frame)
        self.alignment_type_frame_2.setMinimumSize(QtCore.QSize(205, 45))
        self.alignment_type_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.alignment_type_frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.alignment_type_frame_2.setObjectName("alignment_type_frame_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.alignment_type_frame_2)
        self.horizontalLayout_11.setContentsMargins(50, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.global_alignment = QtWidgets.QRadioButton(self.alignment_type_frame_2)
        self.global_alignment.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.global_alignment.setObjectName("global_alignment")
        self.horizontalLayout_11.addWidget(self.global_alignment)
        self.local_alignment = QtWidgets.QRadioButton(self.alignment_type_frame_2)
        self.local_alignment.setStyleSheet("font: 12pt \"Broadway\";\n"
"color: rgb(255, 255, 255);;")
        self.local_alignment.setObjectName("local_alignment")
        self.horizontalLayout_11.addWidget(self.local_alignment)
        self.verticalLayout.addWidget(self.alignment_type_frame_2)
        self.horizontalLayout.addWidget(self.alignment_type_frame)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dna_result_viewer = QtWidgets.QTextEdit(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        self.dna_result_viewer.setFont(font)
        self.dna_result_viewer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"text-align: center;")
        self.dna_result_viewer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dna_result_viewer.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dna_result_viewer.setDocumentTitle("")
        self.dna_result_viewer.setReadOnly(True)
        self.dna_result_viewer.setObjectName("dna_result_viewer")
        self.horizontalLayout_2.addWidget(self.dna_result_viewer)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_9)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.metric_1_label = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(12)
        self.metric_1_label.setFont(font)
        self.metric_1_label.setStyleSheet("color: rgb(255,255,255);")
        self.metric_1_label.setObjectName("metric_1_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.metric_1_label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setStyleSheet("color : rgb(255,255,255);")
        self.doubleSpinBox.setWrapping(True)
        self.doubleSpinBox.setFrame(True)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setReadOnly(True)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setDecimals(2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_8)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.metric_2_label = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(12)
        self.metric_2_label.setFont(font)
        self.metric_2_label.setStyleSheet("color: rgb(255,255,255);")
        self.metric_2_label.setObjectName("metric_2_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.metric_2_label)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(12)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setStyleSheet("color : rgb(255,255,255);")
        self.doubleSpinBox_2.setWrapping(True)
        self.doubleSpinBox_2.setFrame(True)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setReadOnly(True)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.metric_3_label = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(12)
        self.metric_3_label.setFont(font)
        self.metric_3_label.setStyleSheet("color: rgb(255,255,255);")
        self.metric_3_label.setObjectName("metric_3_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.metric_3_label)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(12)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setStyleSheet("color : rgb(255,255,255);")
        self.doubleSpinBox_3.setWrapping(True)
        self.doubleSpinBox_3.setFrame(True)
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_3.setReadOnly(True)
        self.doubleSpinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_3)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_4.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DNA Alignment"))
        self.browse_button_1.setText(_translate("MainWindow", "Browse"))
        self.add_file_button.setText(_translate("MainWindow", "Add File"))
        self.remove_file_button.setText(_translate("MainWindow", "Remove File"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.download_button.setText(_translate("MainWindow", "Download 🠗"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.pairwise_alignment.setText(_translate("MainWindow", "Pairwise"))
        self.multi_alignment.setText(_translate("MainWindow", "Multi"))
        self.global_alignment.setText(_translate("MainWindow", "Global"))
        self.local_alignment.setText(_translate("MainWindow", "Local"))
        self.dna_result_viewer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Script\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dna_result_viewer.setPlaceholderText(_translate("MainWindow", "Result"))
        self.metric_1_label.setText(_translate("MainWindow", "Metric 1:"))
        self.metric_2_label.setText(_translate("MainWindow", "Metric 2:"))
        self.metric_3_label.setText(_translate("MainWindow", "Metric 3:"))
